added 2 enemies to assets and to prototype scene
DeepRestGames/eco-dungeon pull request #1
Opened 2024-05-22 20:47 UTC by enirfo

2024-05-22 20:49 UTC, enirfo commented on scenes/PrototypeScene_01.tscn
> +[gd_scene load_steps=17 format=3 uid="uid://bo1a11i38vuh7"]
cose strane di godot. help

2024-05-23 19:09 UTC, dughiboogie requested changes
A couple things to be updated following the latest conventions decisions.

Animations and creatures look dope af.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Blutschneke/Blutschneke_02.glb
Missing model scene. Create scene with imported model before committing asset.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Flugschneke/Flugschneke_01.glb
Missing model scene. Create scene with imported model before committing asset.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Flugschneke/Animations/fly.res
Loop mode disabled. Interpolation should be set to `nearest`

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Blutschneke/Animations/walk.res
Loop mode disabled. Interpolation should be set to nearest

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Flugschneke/Materials/Material.002.tres
Change material name.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Flugschneke/Materials/Material.003.tres
Change material name.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Flugschneke/Materials/purple worm side.tres
Change material name to fit camelCase naming convention.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Flugschneke/Materials/purple worm.tres
Change material name to fit camelCase naming convention.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Blutschneke/Materials/purple worm.tres
Change material name to fit camelCase naming convention.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Blutschneke/Materials/purple worm side.tres
Change material name to fit camelCase naming convention.

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Ranaorso/240519_ranaorso_01.glb
Change name to fit camelCase naming convention.

2024-05-23 19:09 UTC, dughiboogie commented on scenes/PrototypeScene_01.tscn
> +[gd_scene load_steps=17 format=3 uid="uid://bo1a11i38vuh7"]
help is on the way

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Blutschneke/Blutschneke_02.glb
Change file version to fit semantic versioning convention (`Blutschneke_0.0.2`)

2024-05-23 19:09 UTC, dughiboogie commented on assets/3d/creatures/Flugschneke/Flugschneke_01.glb
Change file version to fit semantic versioning convention (Flugschneke_0.0.2)

2024-05-23 19:09 UTC, dughiboogie commented on scenes/PrototypeScene_01.tscn
> +[ext_resource type="PackedScene" uid="uid://c17ilaij47mhf" path="res://assets/3d/creatures/Flugschneke/Flugschneke_01.glb" id="10_jb8dr"]
Update names

2024-05-23 19:09 UTC, dughiboogie commented on scenes/PrototypeScene_01.tscn
Remove editable children from final scenes

2024-05-28 19:56 UTC, dughiboogie approved these changes
Looks good!

2024-05-28 20:07 UTC, merged