Wip/animations
DeepRestGames/eco-dungeon pull request #2
Opened 2024-05-27 18:05 UTC by MattVsTheWorld

Added support for:

- Character outline before objects (required extra materials)
- Rotation of character model
- Deathzone below the world (deleted walls from scene to test it). Death restart game scene
- Animations for idle and walk
- Shooting projectiles in front of character

2024-05-28 20:42 UTC, dughiboogie requested changes
Some changes needed, cool pew pew

2024-05-28 20:42 UTC, dughiboogie commented on assets/3d/zahir/materials/zahir-brown-base.tres
Missing CamelCase

2024-05-28 20:42 UTC, dughiboogie commented on assets/3d/zahir/materials/zahir-brown.tres
Missing CamelCase

2024-05-28 20:42 UTC, dughiboogie commented on assets/3d/zahir/materials/zahir-teal-base.tres
Missing CamelCase

2024-05-28 20:42 UTC, dughiboogie commented on assets/3d/zahir/materials/zahir-teal.tres
Missing CamelCase

2024-05-28 20:42 UTC, dughiboogie commented on assets/3d/zahir/materials/zahir-white-base.tres
Missing CamelCase

2024-05-28 20:42 UTC, dughiboogie commented on assets/3d/zahir/materials/zahir-white.tres
Missing CamelCase

2024-05-28 20:42 UTC, dughiboogie commented on project.godot
> +
```suggestion
```

2024-05-28 20:42 UTC, dughiboogie commented on scripts/Player.gd
> +
```suggestion

```

2024-05-28 20:42 UTC, dughiboogie commented on scripts/Player.gd
> +		var bullet = preload("res://scenes/Projectile.tscn").instantiate()
Preload Projectile scene in file header

2024-05-28 20:42 UTC, dughiboogie commented on scripts/Player.gd
> +	shoot_particle.emitting = true
Find out what this does

2024-05-28 20:42 UTC, dughiboogie commented on scripts/Projectile.gd
> +		# TODO: re-enable once it seems ok
```suggestion

```

2024-06-01 07:20 UTC, MattVsTheWorld commented
Should have fixed all issues

2024-06-01 11:27 UTC, dughiboogie approved these changes
A-very a-good!

2024-06-02 07:44 UTC, merged